### ISSUE TITLE
Segment telemetry POST Connection refused

### ISSUE THREAD

**Issue by MatanyaLoewenthal** [jetpack-io/devbox#70]
Hey,

Anytime I do any dev box command I get the following error:
```
segment 2022/09/06 11:25:58 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp 165.22.57.39:443: connect: connection refused
segment 2022/09/06 11:25:58 ERROR: 1 messages dropped because they failed to be sent and the client was closed
```

**Comment by Lagoja** [comment]
We have a PR #61 that should address this, issue, which is also a duplicate of #60. For now, you can fix this by setting DO_NOT_TRACK=1 in your environment. 

If you're curious about how Devbox uses Segment, you can check out our docs page here: [Telemetry](https://www.jetpack.io/devbox/docs/telemetry/).

**Comment by Lagoja** [comment]
This should be fixed in our next release (0.0.5). Please let us know if you continue seeing this error message

**Comment by kirbycool** [comment]
I was trying out devbox today and am still seeing this issue in 0.0.5
```
❯ devbox version
0.0.5
segment 2022/09/18 16:56:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
segment 2022/09/18 16:56:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
```
